export const products = [
  {
    id: 1,
    name: "Product n°1",
    text: "Avec la forme incurvée de son vaste dossier, le banc d’extérieur Yuri soigne son look exotique, solaire et graphique. La séduction opère au premier coup d’œil. Approchez donc et admirez son tressage au motif graphique et ses pieds inclinés qui signent son profil 60’s irrésistible [...]",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/3/6/c/c36ccbfa2387f4ea5c47760414709f156fe5dffd_BENYUR001PNK_UK_Yuri_Garden_Bench_Multi_Woven_Green_ar3_2_LB02_LS.jpg",
    description: "Avec la forme incurvée de son vaste dossier, le banc d’extérieur Yuri soigne son look exotique, solaire et graphique. La séduction opère au premier coup d’œil. Approchez donc et admirez son tressage au motif graphique et ses pieds inclinés qui signent son profil 60’s irrésistible. Antequam per ponderibus publici ullo valido id nodum cum cum interiret eique abiectis scriptis sine auxilio id placuerat id commentis tractatus mollioribus cum effundendis clandestinis acciri obstaculo curarum ut urgentis obstaculo eique urgentis destitutus scriptis nisu et et ullo acciri commentis ut simulationem tamquam quibusve nimis sine antequam cum mollioribus Caesarem commentis obstaculo tamquam effundendis confidentia conloquiis acciri et valido antequam acciri rebus qua deliberanti ut tamquam incumberet aliis fieret obstaculo tractatus destitutus Gallum acciri deliberanti fieret deliberanti nisu placuerat mollioribus interiret obstaculo nimis proximis confidentia nocturnis tamquam et cogitabat rebus valido confidentia nisu per codicem quibusve deliberanti commentis simulationem.Accenderat super his incitatum propositum ad nocendum aliqua mulier vilis, quae ad palatium ut poposcerat intromissa insidias ei latenter obtendi prodiderat a militibus obscurissimis. quam Constantina exultans ut in tuto iam locata mariti salute muneratam vehiculoque inpositam per regiae ianuas emisit in publicum, ut his inlecebris alios quoque ad indicanda proliceret paria vel maiora."
  },
    {
    id: 2,
    name: "Product n°2",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/6/b/a/c6ba2777fe78a6fc2b6cf5145db6f922f1dcddeb_SETEMU002SGY_UK_Emu_Garden_Powder_coated_Steel_Set_4_Round_Dining_Set_Soft_Grey_ar3_2_LB02_LS.jpg",
    text: "Emu, ensemble de jardin table ronde et 4 chaises. En italien, al fresco signifie « en plein air », et c’est exactement là que vous emmène l’ensemble table et chaises Emu. Beau et sobre avec sa structure minimaliste et son design monochromatique, il apportera une touche de style et de convivialité à votre extérieur [...]",
    description: "Emu, ensemble de jardin table ronde et 4 chaises. En italien, al fresco signifie « en plein air », et c’est exactement là que vous emmène l’ensemble table et chaises Emu. Beau et sobre avec sa structure minimaliste et son design monochromatique, il apportera une touche de style et de convivialité à votre extérieur. BIam in altera philosophiae parte. quae est quaerendi ac disserendi, quae logikh dicitur, iste vester plane, ut mihi quidem videtur, inermis ac nudus est. tollit definitiones, nihil de dividendo ac partiendo docet, non quo modo efficiatur concludaturque ratio tradit, non qua via captiosa solvantur ambigua distinguantur ostendit; iudicia rerum in sensibus ponit, quibus si semel aliquid falsi pro vero probatum sit, sublatum esse omne iudicium veri et falsi putat.                                 Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur.       Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes.                           Ideoque fertur neminem aliquando ob haec vel similia poenae addictum oblato de more elogio revocari iussisse, quod inexorabiles quoque principes factitarunt. et exitiale hoc vitium, quod in aliis non numquam intepescit, in illo aetatis progressu effervescebat, obstinatum eius propositum accendente adulatorum cohorte.                                 Nam sole orto magnitudine angusti gurgitis sed profundi a transitu arcebantur et dum piscatorios quaerunt lenunculos vel innare temere contextis cratibus parant, effusae legiones, quae hiemabant tunc apud Siden, isdem impetu occurrere veloci. et signis prope ripam locatis ad manus comminus conserendas denseta scutorum conpage semet scientissime praestruebant, ausos quoque aliquos fiducia nandi vel cavatis arborum truncis amnem permeare latenter facillime trucidarunt."
  },
    {
    id: 3,
    name: "Product n°3",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/2/5/1/5/25156ec4a0ce2d672c314d1b157a628a1c836576_OACJOS005BLK_UK_Josper_Low_Compact_Metal_Firepit_Black_ar3_2_LB02_LS.jpg",
    text: "Déclarez votre flamme à Josper, un design fonctionnel à la silhouette élégante et moderne. Imaginé par le Studio MADE, ce brasero est fabriqué dans un métal robuste. Dans un noir profond, il trouvera sans peine sa place dans votre espace extérieur. La vasque ronde n’est pas attachée à sa base [...]",
    description: "Déclarez votre flamme à Josper, un design fonctionnel à la silhouette élégante et moderne. Imaginé par le Studio MADE, ce brasero est fabriqué dans un métal robuste. Dans un noir profond, il trouvera sans peine sa place dans votre espace extérieur. La vasque ronde n’est pas attachée à sa base. Postremo ad id indignitatis est ventum, ut cum peregrini ob formidatam haut ita dudum alimentorum inopiam pellerentur ab urbe praecipites, sectatoribus disciplinarum liberalium inpendio paucis sine respiratione ulla extrusis, tenerentur minimarum adseclae veri, quique id simularunt ad tempus, et tria milia saltatricum ne interpellata quidem cum choris totidemque remanerent magistris."
  },
    {
    id: 4,
    name: "Product n°4",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/8/2/8/3/8283fbb34c040d402350916c6d99d7230adc2be8_OACKUO001TUR_UK_Kuo_Set_Two_Reactive_Glaze_Ceramic_Planters_Mint_ar3_2_LB02_LS.jpg",
    text: "Kuo, lot de 2 cache-pots, glaçure réactive vert menthe. Ajouter de la couleur – et de la brillance – à votre espace extérieur, Kuo en fait son affaire. L’émaillage réactif de ces cache-pots en céramique donneront un look épanoui, moderne et plein de peps à votre coin de de verdure.Sed maximum est in amicitia parem esse inferiori [...]",
    description: "Kuo, lot de 2 cache-pots, glaçure réactive vert menthe. Ajouter de la couleur – et de la brillance – à votre espace extérieur, Kuo en fait son affaire. L’émaillage réactif de ces cache-pots en céramique donneront un look épanoui, moderne et plein de peps à votre coin de de verdure.Sed maximum est in amicitia parem esse inferiori. Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur. Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes.Ideoque fertur neminem aliquando ob haec vel similia poenae addictum oblato de more elogio revocari iussisse, quod inexorabiles quoque principes factitarunt. et exitiale hoc vitium, quod in aliis non numquam intepescit, in illo aetatis progressu effervescebat, obstinatum eius propositum accendente adulatorum cohorte."
  },
    {
    id: 5,
    name: "Product n°5",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/a/3/1/7/a317fb2bf5589bae97c0d1549d0efeb49f70d264_CHAJNH009NAT_UK_Jonah_Garden_Armchair_Natural_ar3_2_LB02_LS.jpg",
    text: "Profitez de la belle saison en aménageant un espace cosy en plein air. Le fauteuil Jonah sera l’allié idéal de vos moments détente au soleil. Un côté rétro se dégage de ses lignes galbées et épurées. Le dossier fuselé, intégré à la structure, l’assise moelleuse et les pieds inclinés créent ce contraste harmonieux [...]",
    description: "Profitez de la belle saison en aménageant un espace cosy en plein air. Le fauteuil Jonah sera l’allié idéal de vos moments détente au soleil. Un côté rétro se dégage de ses lignes galbées et épurées. Le dossier fuselé, intégré à la structure, l’assise moelleuse et les pieds inclinés créent ce contraste harmonieux. Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur.       Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes. Ideoque fertur neminem aliquando ob haec vel similia poenae addictum oblato de more elogio revocari iussisse, quod inexorabiles quoque principes factitarunt. et exitiale hoc vitium, quod in aliis non numquam intepescit, in illo aetatis progressu effervescebat, obstinatum eius propositum accendente adulatorum cohorte. "
  },
    {
    id: 6,
    name: "Product n°6",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/e/c/f/cecf26b15688a9193c11a08cc6863033653ccc80_OACRAZ003BLK_UK_Razan_Set_Two_Tall_Galvanized_Square_Planters_Black_ar3_2_LB02_LS.jpg",
    text: "Sobres et minimalistes, les cache-pots Razan s’intègrent dans votre jardin, quel que soit le style de votre décoration extérieure. Couleur noire pour la note classique et métal galvanisé résolument contemporain, ces créations mettent vos plantes sur le devant de la scène [...]",
    description: "Sobres et minimalistes, les cache-pots Razan s’intègrent dans votre jardin, quel que soit le style de votre décoration extérieure. Couleur noire pour la note classique et métal galvanisé résolument contemporain, ces créations mettent vos plantes sur le devant de la scène. Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur.       Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes. "
  },
  {
    id: 7,
    name: "Product n°7",
    text: "Avec la forme incurvée de son vaste dossier, le banc d’extérieur Yuri soigne son look exotique, solaire et graphique. La séduction opère au premier coup d’œil. Approchez donc et admirez son tressage au motif graphique et ses pieds inclinés qui signent son profil 60’s irrésistible [...]",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/3/6/c/c36ccbfa2387f4ea5c47760414709f156fe5dffd_BENYUR001PNK_UK_Yuri_Garden_Bench_Multi_Woven_Green_ar3_2_LB02_LS.jpg",
    description: "Avec la forme incurvée de son vaste dossier, le banc d’extérieur Yuri soigne son look exotique, solaire et graphique. La séduction opère au premier coup d’œil. Approchez donc et admirez son tressage au motif graphique et ses pieds inclinés qui signent son profil 60’s irrésistible. Antequam per ponderibus publici ullo valido id nodum cum cum interiret eique abiectis scriptis sine auxilio id placuerat id commentis tractatus mollioribus cum effundendis clandestinis acciri obstaculo curarum ut urgentis obstaculo eique urgentis destitutus scriptis nisu et et ullo acciri commentis ut simulationem tamquam quibusve nimis sine antequam cum mollioribus Caesarem commentis obstaculo tamquam effundendis confidentia conloquiis acciri et valido antequam acciri rebus qua deliberanti ut tamquam incumberet aliis fieret obstaculo tractatus destitutus Gallum acciri deliberanti fieret deliberanti nisu placuerat mollioribus interiret obstaculo nimis proximis confidentia nocturnis tamquam et cogitabat rebus valido confidentia nisu per codicem quibusve deliberanti commentis simulationem.Accenderat super his incitatum propositum ad nocendum aliqua mulier vilis, quae ad palatium ut poposcerat intromissa insidias ei latenter obtendi prodiderat a militibus obscurissimis. quam Constantina exultans ut in tuto iam locata mariti salute muneratam vehiculoque inpositam per regiae ianuas emisit in publicum, ut his inlecebris alios quoque ad indicanda proliceret paria vel maiora."
  },
    {
    id: 8,
    name: "Product n°8",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/6/b/a/c6ba2777fe78a6fc2b6cf5145db6f922f1dcddeb_SETEMU002SGY_UK_Emu_Garden_Powder_coated_Steel_Set_4_Round_Dining_Set_Soft_Grey_ar3_2_LB02_LS.jpg",
    text: "Emu, ensemble de jardin table ronde et 4 chaises. En italien, al fresco signifie « en plein air », et c’est exactement là que vous emmène l’ensemble table et chaises Emu. Beau et sobre avec sa structure minimaliste et son design monochromatique, il apportera une touche de style et de convivialité à votre extérieur [...]",
    description: "Emu, ensemble de jardin table ronde et 4 chaises. En italien, al fresco signifie « en plein air », et c’est exactement là que vous emmène l’ensemble table et chaises Emu. Beau et sobre avec sa structure minimaliste et son design monochromatique, il apportera une touche de style et de convivialité à votre extérieur. BIam in altera philosophiae parte. quae est quaerendi ac disserendi, quae logikh dicitur, iste vester plane, ut mihi quidem videtur, inermis ac nudus est. tollit definitiones, nihil de dividendo ac partiendo docet, non quo modo efficiatur concludaturque ratio tradit, non qua via captiosa solvantur ambigua distinguantur ostendit; iudicia rerum in sensibus ponit, quibus si semel aliquid falsi pro vero probatum sit, sublatum esse omne iudicium veri et falsi putat.                                 Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur.       Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes.                           Ideoque fertur neminem aliquando ob haec vel similia poenae addictum oblato de more elogio revocari iussisse, quod inexorabiles quoque principes factitarunt. et exitiale hoc vitium, quod in aliis non numquam intepescit, in illo aetatis progressu effervescebat, obstinatum eius propositum accendente adulatorum cohorte.                                 Nam sole orto magnitudine angusti gurgitis sed profundi a transitu arcebantur et dum piscatorios quaerunt lenunculos vel innare temere contextis cratibus parant, effusae legiones, quae hiemabant tunc apud Siden, isdem impetu occurrere veloci. et signis prope ripam locatis ad manus comminus conserendas denseta scutorum conpage semet scientissime praestruebant, ausos quoque aliquos fiducia nandi vel cavatis arborum truncis amnem permeare latenter facillime trucidarunt."
  },
    {
    id: 9,
    name: "Product n°9",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/2/5/1/5/25156ec4a0ce2d672c314d1b157a628a1c836576_OACJOS005BLK_UK_Josper_Low_Compact_Metal_Firepit_Black_ar3_2_LB02_LS.jpg",
    text: "Déclarez votre flamme à Josper, un design fonctionnel à la silhouette élégante et moderne. Imaginé par le Studio MADE, ce brasero est fabriqué dans un métal robuste. Dans un noir profond, il trouvera sans peine sa place dans votre espace extérieur. La vasque ronde n’est pas attachée à sa base [...]",
    description: "Déclarez votre flamme à Josper, un design fonctionnel à la silhouette élégante et moderne. Imaginé par le Studio MADE, ce brasero est fabriqué dans un métal robuste. Dans un noir profond, il trouvera sans peine sa place dans votre espace extérieur. La vasque ronde n’est pas attachée à sa base. Postremo ad id indignitatis est ventum, ut cum peregrini ob formidatam haut ita dudum alimentorum inopiam pellerentur ab urbe praecipites, sectatoribus disciplinarum liberalium inpendio paucis sine respiratione ulla extrusis, tenerentur minimarum adseclae veri, quique id simularunt ad tempus, et tria milia saltatricum ne interpellata quidem cum choris totidemque remanerent magistris."
  },
    {
    id: 10,
    name: "Product n°10",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/8/2/8/3/8283fbb34c040d402350916c6d99d7230adc2be8_OACKUO001TUR_UK_Kuo_Set_Two_Reactive_Glaze_Ceramic_Planters_Mint_ar3_2_LB02_LS.jpg",
    text: "Kuo, lot de 2 cache-pots, glaçure réactive vert menthe. Ajouter de la couleur – et de la brillance – à votre espace extérieur, Kuo en fait son affaire. L’émaillage réactif de ces cache-pots en céramique donneront un look épanoui, moderne et plein de peps à votre coin de de verdure.Sed maximum est in amicitia parem esse inferiori [...]",
    description: "Kuo, lot de 2 cache-pots, glaçure réactive vert menthe. Ajouter de la couleur – et de la brillance – à votre espace extérieur, Kuo en fait son affaire. L’émaillage réactif de ces cache-pots en céramique donneront un look épanoui, moderne et plein de peps à votre coin de de verdure.Sed maximum est in amicitia parem esse inferiori. Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur. Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes.Ideoque fertur neminem aliquando ob haec vel similia poenae addictum oblato de more elogio revocari iussisse, quod inexorabiles quoque principes factitarunt. et exitiale hoc vitium, quod in aliis non numquam intepescit, in illo aetatis progressu effervescebat, obstinatum eius propositum accendente adulatorum cohorte."
  },
    {
    id: 11,
    name: "Product n°11",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/a/3/1/7/a317fb2bf5589bae97c0d1549d0efeb49f70d264_CHAJNH009NAT_UK_Jonah_Garden_Armchair_Natural_ar3_2_LB02_LS.jpg",
    text: "Profitez de la belle saison en aménageant un espace cosy en plein air. Le fauteuil Jonah sera l’allié idéal de vos moments détente au soleil. Un côté rétro se dégage de ses lignes galbées et épurées. Le dossier fuselé, intégré à la structure, l’assise moelleuse et les pieds inclinés créent ce contraste harmonieux [...]",
    description: "Profitez de la belle saison en aménageant un espace cosy en plein air. Le fauteuil Jonah sera l’allié idéal de vos moments détente au soleil. Un côté rétro se dégage de ses lignes galbées et épurées. Le dossier fuselé, intégré à la structure, l’assise moelleuse et les pieds inclinés créent ce contraste harmonieux. Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur.       Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes. Ideoque fertur neminem aliquando ob haec vel similia poenae addictum oblato de more elogio revocari iussisse, quod inexorabiles quoque principes factitarunt. et exitiale hoc vitium, quod in aliis non numquam intepescit, in illo aetatis progressu effervescebat, obstinatum eius propositum accendente adulatorum cohorte. "
  },
    {
    id: 12,
    name: "Product n°12",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/e/c/f/cecf26b15688a9193c11a08cc6863033653ccc80_OACRAZ003BLK_UK_Razan_Set_Two_Tall_Galvanized_Square_Planters_Black_ar3_2_LB02_LS.jpg",
    text: "Sobres et minimalistes, les cache-pots Razan s’intègrent dans votre jardin, quel que soit le style de votre décoration extérieure. Couleur noire pour la note classique et métal galvanisé résolument contemporain, ces créations mettent vos plantes sur le devant de la scène [...]",
    description: "Sobres et minimalistes, les cache-pots Razan s’intègrent dans votre jardin, quel que soit le style de votre décoration extérieure. Couleur noire pour la note classique et métal galvanisé résolument contemporain, ces créations mettent vos plantes sur le devant de la scène. Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur.       Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes. "
  },{
    id: 13,
    name: "Product n°13",
    text: "Avec la forme incurvée de son vaste dossier, le banc d’extérieur Yuri soigne son look exotique, solaire et graphique. La séduction opère au premier coup d’œil. Approchez donc et admirez son tressage au motif graphique et ses pieds inclinés qui signent son profil 60’s irrésistible [...]",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/3/6/c/c36ccbfa2387f4ea5c47760414709f156fe5dffd_BENYUR001PNK_UK_Yuri_Garden_Bench_Multi_Woven_Green_ar3_2_LB02_LS.jpg",
    description: "Avec la forme incurvée de son vaste dossier, le banc d’extérieur Yuri soigne son look exotique, solaire et graphique. La séduction opère au premier coup d’œil. Approchez donc et admirez son tressage au motif graphique et ses pieds inclinés qui signent son profil 60’s irrésistible. Antequam per ponderibus publici ullo valido id nodum cum cum interiret eique abiectis scriptis sine auxilio id placuerat id commentis tractatus mollioribus cum effundendis clandestinis acciri obstaculo curarum ut urgentis obstaculo eique urgentis destitutus scriptis nisu et et ullo acciri commentis ut simulationem tamquam quibusve nimis sine antequam cum mollioribus Caesarem commentis obstaculo tamquam effundendis confidentia conloquiis acciri et valido antequam acciri rebus qua deliberanti ut tamquam incumberet aliis fieret obstaculo tractatus destitutus Gallum acciri deliberanti fieret deliberanti nisu placuerat mollioribus interiret obstaculo nimis proximis confidentia nocturnis tamquam et cogitabat rebus valido confidentia nisu per codicem quibusve deliberanti commentis simulationem.Accenderat super his incitatum propositum ad nocendum aliqua mulier vilis, quae ad palatium ut poposcerat intromissa insidias ei latenter obtendi prodiderat a militibus obscurissimis. quam Constantina exultans ut in tuto iam locata mariti salute muneratam vehiculoque inpositam per regiae ianuas emisit in publicum, ut his inlecebris alios quoque ad indicanda proliceret paria vel maiora."
  },
    {
    id: 14,
    name: "Product n°14",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/6/b/a/c6ba2777fe78a6fc2b6cf5145db6f922f1dcddeb_SETEMU002SGY_UK_Emu_Garden_Powder_coated_Steel_Set_4_Round_Dining_Set_Soft_Grey_ar3_2_LB02_LS.jpg",
    text: "Emu, ensemble de jardin table ronde et 4 chaises. En italien, al fresco signifie « en plein air », et c’est exactement là que vous emmène l’ensemble table et chaises Emu. Beau et sobre avec sa structure minimaliste et son design monochromatique, il apportera une touche de style et de convivialité à votre extérieur [...]",
    description: "Emu, ensemble de jardin table ronde et 4 chaises. En italien, al fresco signifie « en plein air », et c’est exactement là que vous emmène l’ensemble table et chaises Emu. Beau et sobre avec sa structure minimaliste et son design monochromatique, il apportera une touche de style et de convivialité à votre extérieur. BIam in altera philosophiae parte. quae est quaerendi ac disserendi, quae logikh dicitur, iste vester plane, ut mihi quidem videtur, inermis ac nudus est. tollit definitiones, nihil de dividendo ac partiendo docet, non quo modo efficiatur concludaturque ratio tradit, non qua via captiosa solvantur ambigua distinguantur ostendit; iudicia rerum in sensibus ponit, quibus si semel aliquid falsi pro vero probatum sit, sublatum esse omne iudicium veri et falsi putat.                                 Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur.       Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes.                           Ideoque fertur neminem aliquando ob haec vel similia poenae addictum oblato de more elogio revocari iussisse, quod inexorabiles quoque principes factitarunt. et exitiale hoc vitium, quod in aliis non numquam intepescit, in illo aetatis progressu effervescebat, obstinatum eius propositum accendente adulatorum cohorte.                                 Nam sole orto magnitudine angusti gurgitis sed profundi a transitu arcebantur et dum piscatorios quaerunt lenunculos vel innare temere contextis cratibus parant, effusae legiones, quae hiemabant tunc apud Siden, isdem impetu occurrere veloci. et signis prope ripam locatis ad manus comminus conserendas denseta scutorum conpage semet scientissime praestruebant, ausos quoque aliquos fiducia nandi vel cavatis arborum truncis amnem permeare latenter facillime trucidarunt."
  },
    {
    id: 15,
    name: "Product n°15",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/2/5/1/5/25156ec4a0ce2d672c314d1b157a628a1c836576_OACJOS005BLK_UK_Josper_Low_Compact_Metal_Firepit_Black_ar3_2_LB02_LS.jpg",
    text: "Déclarez votre flamme à Josper, un design fonctionnel à la silhouette élégante et moderne. Imaginé par le Studio MADE, ce brasero est fabriqué dans un métal robuste. Dans un noir profond, il trouvera sans peine sa place dans votre espace extérieur. La vasque ronde n’est pas attachée à sa base [...]",
    description: "Déclarez votre flamme à Josper, un design fonctionnel à la silhouette élégante et moderne. Imaginé par le Studio MADE, ce brasero est fabriqué dans un métal robuste. Dans un noir profond, il trouvera sans peine sa place dans votre espace extérieur. La vasque ronde n’est pas attachée à sa base. Postremo ad id indignitatis est ventum, ut cum peregrini ob formidatam haut ita dudum alimentorum inopiam pellerentur ab urbe praecipites, sectatoribus disciplinarum liberalium inpendio paucis sine respiratione ulla extrusis, tenerentur minimarum adseclae veri, quique id simularunt ad tempus, et tria milia saltatricum ne interpellata quidem cum choris totidemque remanerent magistris."
  },
    {
    id: 16,
    name: "Product n°16",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/8/2/8/3/8283fbb34c040d402350916c6d99d7230adc2be8_OACKUO001TUR_UK_Kuo_Set_Two_Reactive_Glaze_Ceramic_Planters_Mint_ar3_2_LB02_LS.jpg",
    text: "Kuo, lot de 2 cache-pots, glaçure réactive vert menthe. Ajouter de la couleur – et de la brillance – à votre espace extérieur, Kuo en fait son affaire. L’émaillage réactif de ces cache-pots en céramique donneront un look épanoui, moderne et plein de peps à votre coin de de verdure.Sed maximum est in amicitia parem esse inferiori [...]",
    description: "Kuo, lot de 2 cache-pots, glaçure réactive vert menthe. Ajouter de la couleur – et de la brillance – à votre espace extérieur, Kuo en fait son affaire. L’émaillage réactif de ces cache-pots en céramique donneront un look épanoui, moderne et plein de peps à votre coin de de verdure.Sed maximum est in amicitia parem esse inferiori. Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur. Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes.Ideoque fertur neminem aliquando ob haec vel similia poenae addictum oblato de more elogio revocari iussisse, quod inexorabiles quoque principes factitarunt. et exitiale hoc vitium, quod in aliis non numquam intepescit, in illo aetatis progressu effervescebat, obstinatum eius propositum accendente adulatorum cohorte."
  },
    {
    id: 17,
    name: "Product n°17",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/a/3/1/7/a317fb2bf5589bae97c0d1549d0efeb49f70d264_CHAJNH009NAT_UK_Jonah_Garden_Armchair_Natural_ar3_2_LB02_LS.jpg",
    text: "Profitez de la belle saison en aménageant un espace cosy en plein air. Le fauteuil Jonah sera l’allié idéal de vos moments détente au soleil. Un côté rétro se dégage de ses lignes galbées et épurées. Le dossier fuselé, intégré à la structure, l’assise moelleuse et les pieds inclinés créent ce contraste harmonieux [...]",
    description: "Profitez de la belle saison en aménageant un espace cosy en plein air. Le fauteuil Jonah sera l’allié idéal de vos moments détente au soleil. Un côté rétro se dégage de ses lignes galbées et épurées. Le dossier fuselé, intégré à la structure, l’assise moelleuse et les pieds inclinés créent ce contraste harmonieux. Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur.       Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes. Ideoque fertur neminem aliquando ob haec vel similia poenae addictum oblato de more elogio revocari iussisse, quod inexorabiles quoque principes factitarunt. et exitiale hoc vitium, quod in aliis non numquam intepescit, in illo aetatis progressu effervescebat, obstinatum eius propositum accendente adulatorum cohorte. "
  },
    {
    id: 18,
    name: "Product n°18",
    src: "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/e/c/f/cecf26b15688a9193c11a08cc6863033653ccc80_OACRAZ003BLK_UK_Razan_Set_Two_Tall_Galvanized_Square_Planters_Black_ar3_2_LB02_LS.jpg",
    text: "Sobres et minimalistes, les cache-pots Razan s’intègrent dans votre jardin, quel que soit le style de votre décoration extérieure. Couleur noire pour la note classique et métal galvanisé résolument contemporain, ces créations mettent vos plantes sur le devant de la scène [...]",
    description: "Sobres et minimalistes, les cache-pots Razan s’intègrent dans votre jardin, quel que soit le style de votre décoration extérieure. Couleur noire pour la note classique et métal galvanisé résolument contemporain, ces créations mettent vos plantes sur le devant de la scène. Iam virtutem ex consuetudine vitae sermonisque nostri interpretemur nec eam, ut quidam docti, verborum magnificentia metiamur virosque bonos eos, qui habentur, numeremus, Paulos, Catones, Galos, Scipiones, Philos; his communis vita contenta est; eos autem omittamus, qui omnino nusquam reperiuntur.       Alii summum decus in carruchis solito altioribus et ambitioso vestium cultu ponentes sudant sub ponderibus lacernarum, quas in collis insertas cingulis ipsis adnectunt nimia subtegminum tenuitate perflabiles, expandentes eas crebris agitationibus maximeque sinistra, ut longiores fimbriae tunicaeque perspicue luceant varietate liciorum effigiatae in species animalium multiformes. "
  },
];
